### ISSUE TITLE
[솝커톤] 웹 4조 과제

### ISSUE THREAD

**Issue by sjk4618** [AND-SOPT-SERVER/forum#40]
**[요구사항 분석]**

- 유저가 있음
- 유저가 실패글을 작성, 조회할 수 있음
- 유저가 실패글에 이모지를 누를수있음(이모지 총 개수 4개 중에 1개만 선택가능함 -> 유니크키 설정함)
- 내 실패글만 조회가능함
- 실패글 상세조회 가능함
- 이모지 합계 많은 순서로 베스트 5 정렬 조회 가능함

**[공수 산정]**
- 혼자했습니다...
- 서버 4시까지 한다고 처음 말씀드렸었고, 3시쯤 구현완료하였습니다.
- cors 테스트는 4시에 진행(웹과 함께)

**[설계도 작성]**

- API 명세서 : https://robust-afternoon-18b.notion.site/API-144ef33dfa818136ad85f2638813e9c3?pvs=4
  - 수정시간 기입했고, 수정내용은 실시간으로 전달했습니다.
- ERD
<img width="846" alt="스크린샷 2024-11-24 04 41 46" src="https://github.com/user-attachments/assets/6c6c95e6-defe-4c30-b3e0-9108a28308d9">

**Comment by daehwan2da** [comment]
성준 혼자 맡겨서 너무 미안했는데 설계도, 구현도, 완성도도 너무 완벽했습니다
많이 도움 못준것같아 미안할 따름이군요

많이 성장한 솝커톤이되었기를 바랍니다
고생하셨습니다
