### ISSUE TITLE
[솝커톤] 안드로이드 3조 과제

### ISSUE THREAD

**Issue by yxinot** [AND-SOPT-SERVER/forum#41]
# 요구사항 분석

- [x]  Even if “비록 ~ 일지라도” 의미에 맞게 사용자에게 한 줄 감사 일기를 입력 받아 구슬 하나 생성
- [x]  구슬의 수가 8개가 될 시, 왕구슬로 변화
- [x]  왕구슬에는 8개 구슬 감사 일기 내용 중 랜덤으로 하나의 내용을 넣어 생성
- [x]  전체 왕구슬 목록 조회

# 공수 산정

위에 데이터베이스(표) 링크

https://www.notion.so/5a9e1553190c4d7c9d66c0c875c6f697?v=e4da693806d1498da234b8e1e32a9612&pvs=4

# 설계도 작성

## API 명세서

https://www.notion.so/1446fb5ba03781d786c5f8ab695915ab?v=1446fb5ba03781fd8078000cf9a82c98&pvs=4

## ERD
<img width="764" alt="스크린샷 2024-11-24 오전 5 09 52" src="https://github.com/user-attachments/assets/2faa28ed-ed4f-4eb1-b226-9a200903febc">

**Comment by daehwan2da** [comment]
예린 채현 설계도 구현도 시간 내에 잘 마무리해서 훌륭합니다
중간에 이미지 업로드관련 스펙이 추가될 수 있었지만, 침착히 구현가능하다고 기획측에 조율하는 모습이 인상깊었고
이렇듯 프로젝트 중간에 갑작스럽게 추가되는 스펙을 앞으로 많이 경험할텐데 이번 솝커톤으로 많은 배운점이있었으면 합니다~

고생하셨습니다
