### ISSUE TITLE
[솝커톤] ios 3조 과제

### ISSUE THREAD

**Issue by gahyuun** [AND-SOPT-SERVER/forum#43]
# 기능

- 사용자는 오늘 마시고 싶은 술양(주량)과 이름을 입력할 수 있습니다.
- 맛있게 술을 마시면서, 한 잔 마실 때마다 탭을 누르고 탭을 누를 때마다 1잔씩 적립됩니다.
- 1잔씩 적립될때마다 주량을 넘었는지 확인합니다.
- 주량이 넘었을 때 사용자는 맞춤형 페이크 사진을 전달 받을 수 있습니다.
- 사용자는 재설정 버튼을 통해서 오늘 마시고 싶은 술양(주량)과 이름을 다시 설정할 수 있습니다.

# API 명세서, ERD

명세서에 공수산정 포함됐습니다

API 
https://www.notion.so/API-326b1a1e5a2c4484a286418ceed16423?pvs=21)](https://www.notion.so/API-326b1a1e5a2c4484a286418ceed16423?pvs=21

ERD
https://luminous-chard-386.notion.site/ERD-cc1dcfa52ccf41c2ba06f2d722d47d6c?pvs=4](https://www.notion.so/ERD-cc1dcfa52ccf41c2ba06f2d722d47d6c?pvs=21

**Comment by daehwan2da** [comment]
다진 가현 두 분이서 아주 완벽한 팀웍을 보여주신듯합니다
구현도 가장 빨리 한 편에 속하고, 설계도 깜끔하네요

YB 두 분이서 아주 잘 하셨고, 많은 배움이 있는 솝커톤 되었으면 합니다~
