### ISSUE TITLE
[솝커톤] 안드 1조 과제

### ISSUE THREAD

**Issue by Jang99u** [AND-SOPT-SERVER/forum#44]
### 주요 기능
- 술자리 첫번째 단골 질문, "너 주량이 얼마야?"
- "알콜 단위 계산법"을 기반으로 공식적인 주량 JP 설정
- "SOPT 내 내 전체 주량은 몇등?" 파트별, 전체 SOPT 내에서 내 주량 랭킹 확인 가능 ㅋㅋ

### 수민
- 짠- BTI , 주량 산정을 위한 유저 정보  등록 API 구현했습니다.
- 주량 산정 로직을 구현했습니다.
- 마이페이지(홈화면) 에서 유저 정보를 불러오는 API를 구현했습니다.

### 장규
- SOPT 전체 혹은 파트 내에서 내 주량 랭킹 API 구현했습니다.
- 전체 랭킹과 파트별 랭킹을 따로 구해야하기에 별도의 쿼리문을 작성해서 관리했습니다.

### 역할 분담 
`유저 등록 API` `마이페이지 조회 API` 구현 : 수민
12:00 ~ 2:00 구현 
2:00 ~ 3:00 리팩터링 진행

`배포 준비` : 장규
1:00 ~ 2:00

`유저 회원가입 정보 확인 API` `랭킹 정보 조회 API` 구현 : 장규
2:00 ~ 5:00 구현

### ERD
<img width="487" alt="image" src="https://github.com/user-attachments/assets/9246dca8-3803-4ba4-a9e2-45f8622924ef">

### API 명세서
https://pastoral-can-e04.notion.site/8f54de63fae8465fb23b52ff8335542f?v=14727658a0c781d5b4e5000cc6d5ccaa&pvs=4

![img_partranking_profile](https://github.com/user-attachments/assets/36203b7f-89e6-4d2d-8787-407011e7ece1)

![img_large_my_partranking](https://github.com/user-attachments/assets/57a50f50-f239-44bb-bbfb-71caade153e6)

**Comment by daehwan2da** [comment]
장규 수민 구현도, 팀웍도 아주 좋은 모습이 인상깊었어요~
다른 팀에 비해 설계를 늦게 시작했음에도 차분하게 구현을 완성하는 모습이 멋졌습니다

YB 두 분이서 잘 하셨습니다 짱

(근데 저 거북이 넥타이는 장규를 좀 닮은듯하군요)
