### ISSUE TITLE
[솝커톤] IOS 2조 과제

### ISSUE THREAD

**Issue by mr8356** [AND-SOPT-SERVER/forum#45]
<br>
<h2>💡요구사항 분석</h2>
<ul>
<li>현재 상태와 오늘의 퀘스트 조회</li>
<li>퀘스트 상세 정보 조회</li>
<li>퀘스트 사진 인증</li>
<li>퀘스트 성공(경험치 업데이트)</li>
</ul>
<img width="619" alt="스크린샷 2024-11-24 오전 5 06 47" src="https://github.com/user-attachments/assets/9e8ea20d-73d9-404b-8997-a7d66b418a09">
<hr>

## 💡공수 산성

| 작업명 | API Endpoint | 담당자 | 작업 시간 |
| --- | --- | --- | --- |
| 설계 | - | 백세희, 조동현 | 12:00 AM |
| 기본 설계 및 페어 프로그래밍 | - | 백세희, 조동현 | 1:30 AM |
| 현재 상태와 오늘의 퀘스트 조회 개발 | `/api/v1/quests/home` | 조동현 | 4:30 AM |
| 퀘스트 성공 개발 | `/api/v1/quests/success` | 백세희 | 4:30 AM |
| 배포 준비 및 설계 | - | 백세희, 조동현 | 5:00 AM |

---

## 💡설계도 작성
[Diagram Link](https://app.diagrams.net/#G1zLK8KxuER4tjuzC3UJpF5GIo8H_dofGz#%7B%22pageId%22%3A%22FfgBqu-t-IJGkG84fHCm%22%7D)

<img width="632" alt="스크린샷 2024-11-24 오전 7 08 31" src="https://github.com/user-attachments/assets/a4e3edf4-c671-4fd3-8a53-f3506f429aa9">

<img width="397" alt="스크린샷 2024-11-24 오전 5 08 02" src="https://github.com/user-attachments/assets/23125030-0cdd-4257-ab1d-9d13915ee425">

## 💡 [API 명세서](https://www.notion.so/API-145da607282681de961de556432a1b05?pvs=21)

[API 명세서](https://www.notion.so/API-145da607282681de961de556432a1b05?pvs=21)

**Comment by daehwan2da** [comment]
동현 세희 작은 구현에 살 붙히는 모습에 감탄했어요~ 구현도 잘해내셨습니다
설계 구조도 아주 잘봤어요 이렇게 설계를 가시적으로 그리는 습관이 있어야 더 큰 시각으로 앞으로 설계가 가능할거에요
YB 두 분이서 아주 잘 하셨습니다 짱
