### ISSUE TITLE
[솝커톤] iOS 1조 과제

### ISSUE THREAD

**Issue by Yeonnies** [AND-SOPT-SERVER/forum#46]
## [요구사항 분석]

features list-up

- 현재 고민 조회 기능
- 완료된 고민 조회 기능
- 고민 작성 기능
- 고민 사용자가 직접 해결 기능

## [공수 산정]

현재 고민 조회 기능, 완료된 고민 조회 기능, 고민 사용자가 직접 해결 기능 - 치현
고민 작성 기능 - 나연

22:00 ~ 00:00 ERD 작성/ api 설계
00:00 ~ 03:00 api 설계 2개 끝내기
03:00 ~ 06:00 api 설계 끝

## [설계도 작성]

+ API 명세서 주소
https://www.notion.so/API-1449b52a9e7a819eb224cda5d3cab598?pvs=4
+ ERD
<img width="852" alt="스크린샷 2024-11-24 오전 5 37 16" src="https://github.com/user-attachments/assets/5bf4abe5-fec5-4738-98a5-90fc0f4400e1">

**Comment by daehwan2da** [comment]
치현 나연 설계 아주 잘했고 클라연결에 침착히 잘 대응하신것같아서 배우신게 많을거라고 생각들어요~
YB 두 분이서 아주 잘 했습니다 짱
