### ISSUE TITLE
[솝커톤] 안드 4조 과제

### ISSUE THREAD

**Issue by seoyeonjin** [AND-SOPT-SERVER/forum#47]
### [요구사항 분석]
"피하고 싶은 상황, 대신 피할 수 있는 핑계를 생각해주는 앱!"

**1. 사용자의 피하고 싶은 상황 텍스트를 입력받고 그에 해당하는 핑계를 생성해 사용자에게 전달해주어야 한다.**
 - 사용자의 상황 텍스트를 받고 핑계를 전달
 - 사용자의 상황 텍스트와 핑계 데이터를 저장

 **2. 이전의 사용했던 핑계 리스트를 확인할 수 있어야 한다.**
  - 사용자가 이전에 저장했던 핑계 리스트를 전달

 **3. 사용자가 생성한 핑계를 사용했는지, 사용했다면 상황을 회피하는데 성공했는지 여부를 기록한다.** 
  - 사용자가 핑계의 성공 여부를 저장

 **4. 다른 사용자가 유용하게 사용한 핑계를 확인할 수 있다.**
  - 오늘 생성된 다른 사용자의 리뷰 리스트를 전달

### [공수 산정]
역할 분담
전윤혁: 배포, API 4개 개발, GPT API 사용 / 서연진: 명세서 작성, API 3개 개발

10:00 ~ 12:00 윤혁: GPT 연결 및 관련 기능 구현, 연진: 명세서 작성
12:00 ~ 4:00 윤혁: API 3개 개발, 연진: API 2개 개발 
4:00 ~ 5:00 윤혁: API 1개 개발, 연진: API 1개 개발
5:00 ~ 6:00 배포 및 마무리 정리

### [설계도 작성]
![JP (2)](https://github.com/user-attachments/assets/c29a9668-9353-4d44-a24b-418ed304428c)

노션: https://coal-tuesday-acf.notion.site/API-144016235613813bb505dd150367de4b?pvs=4

**Comment by daehwan2da** [comment]
윤혁 연진 gpt 연결이 어려웠을텐데 서버 스펙 잘 조율하면서 구현 잘 해내셨습니다~
YB 두분이서 너무 멋졌습니다 짱
