### ISSUE TITLE
[솝커톤] 웹 2조 과제

### ISSUE THREAD

**Issue by Parkjyun** [AND-SOPT-SERVER/forum#48]
<img width="909" alt="스크린샷 2024-11-24 오전 5 58 25" src="https://github.com/user-attachments/assets/4f0ae97e-dfc5-4aca-a66c-d7c592a603df">

https://sand-newsstand-742.notion.site/Server-145bf49fee5c81718c9fc85dc7ed4b89?pvs=73

**Comment by daehwan2da** [comment]
재연 세은 어려움이 있었지만 정말 차분히 잘 극복해내셨습니다~ 복잡한 설계에도 구현 잘 했어요 짱
