### ISSUE TITLE
[솝커톤] ios 4조 과제

### ISSUE THREAD

**Issue by choyeongju** [AND-SOPT-SERVER/forum#50]
https://zzanggureum.notion.site/7eeb342e83c043c9af8bbe6df46fb7c5?v=147010b478c18102be15000cac14242f&pvs=4

### [역할 분담]
조영주: 배포, API 2개 개발
박상아: API 2개 개발

&nbsp;

### [초기 db 설계]
![image](https://github.com/user-attachments/assets/c869c97f-5a5d-4365-95ee-2f6581adc827)

&nbsp;

### [db 변경]
Member, Question, QuestionElement 3개의 테이블로 축소

**Comment by daehwan2da** [comment]
영주 상아 어려운 설계에도 구현 잘 했어요 짱
