### ISSUE TITLE
와인잔조 8조 1차 세미나 과제

### ISSUE THREAD

**Issue by Parkjyun** [AND-SOPT-SERVER/forum#8]
# 8조 코톡

# 구현 현황

| 기능 | 재연 | 상아 | 세희 | 재민 |
| --- | --- | --- | --- | --- |
| 일기 글자수 30자로 제한 | 완료 | 완료  | 완료  | 완료 |
| 일기 삭제 기능 추가 ⭐️ | 완료 | 완료  | 완료 | 완료 |
| 일기 수정 기능 추가 ⭐️ | 완료 | 완료  | 완료 | 완료 |
| 삭제된 일기 복구 기능 추가 ⭐️⭐️ | 완료 | 완료  | 완료 | X |
| 일기 수정 일일 2회 제한 기능 추가 ⭐️⭐️ | x | 완료  | 고민 | 완료 |
| Application 종료 시에도 일기 저장 목록 유지되는 기능 추가 ⭐️⭐️⭐️ | x | X | 고민 | X |
| 이모지 등을 1글자로 계산하는 기능 추가 ⭐️⭐️⭐️⭐️⭐️ | x | X | 고민 | X |

---

# 재연

### 💡일기 작성 기능

softdelete를 위해 diary에 boolean isDeleted를 추가했습니다.

```java
    //service
    void writeDiary(final String body, final MemoryType memoryType) {
        final Diary diary = new Diary(null, body, false);
        getDiaryRepository(memoryType).save(diary);
    }
    //repositoryImpl
        public void save(final Diary diary) {
        final long id = numbering.addAndGet(1);//1추가하고 추가한 값 return
        diary.setId(id);
        storage.put(id, diary);
    }
    
    
```

### 💡일기 조회 기능

stream을 돌며 삭제되지 않은 다이어리만 갖고옵니다

```java
//service
  List<Diary> getDiaryList(final MemoryType memoryType) {
        return getDiaryRepository(memoryType).findAll();
    }

//repositoryImpl
    public List<Diary> findAll() {
        return storage.values().stream()
                .filter(diary -> !diary.getIsDeleted())
                .toList();
    }
```

### 💡일기 수정 기능

```java
//service
  void patchDiary(final long id, final String body, final MemoryType memoryType) {
        getDiaryRepository(memoryType).patch(id, body);
    }

//repositoryImpl
    public void patch(final long id, final String body) {
        Diary diary = storage.get(id);
        validateRetrieval(diary);
        diary.setBody(body);
        storage.put(diary.getId(), diary);
    }
```

### 💡일기 제거 기능

isDeleted를 true로 변경합니다.

```java
//service
    void deleteDiary(final long id, final MemoryType memoryType) {
        getDiaryRepository(memoryType).delete(id);
    }

//repositoryImpl

    public void delete(long id) {
        Diary diary = storage.get(id);
        validateRetrieval(diary);
        diary.setIsDeleted(true);
        storage.put(diary.getId(), diary);
    }
```

## 📍고민 내용

 

- 스프링빈을 런타임에 갈아끼우듯, 전략패턴을 적용하여 런타임에 DiaryRepository를 구현한 FileDiaryRepository, MemoryDiaryRepository를 선택하도록 했습니다.
    
    이를 위해 사용자 입력에서 기존 매개변수들뿐만 아니라 Enum으로 정의한 MemoryType을 받도록 했습니다.
    
- 기존에는 DiaryService의 생성자에서 diaryRepositoryMap에 들어갈 key, value를 직접 넣어주었지만, 변경에 닫혀 있는 것 같아 이를 Main에서 의존성 주입을 받도록 변경했습니다.
- 그런데 현재 main은 ui에 대한 책임만 지고 있는 클래스 같아 따로 의존성을 주입해주는 factory 클래스를 만들어야 했나 싶네요.

```java
//변경 전
public class DiaryService {
    private final DiaryRepository diaryRepository = new DiaryRepository();
    
    DiaryService () {
        diaryRepositoryMap = new HashMap<>();
        diaryRepositoryMap.put(MemoryType.FILE, new FileDiaryRepository());
        diaryRepositoryMap.put(MemoryType.MEMORY, new MemoryDiaryRepository());
    }
    
     private DiaryRepository getDiaryRepository(MemoryType memoryType) {
        DiaryRepository repository = diaryRepositoryMap.get(memoryType);
        if (repository == null) {
            throw new IllegalArgumentException("해당 MemoryType에 맞는 Repository가 없습니다: " + memoryType);
        }
        return repository;
    }
}

//변경 후
public class DiaryService {
    private Map<MemoryType, DiaryRepository> diaryRepositoryMap;

    DiaryService (Map<MemoryType, DiaryRepository> diaryRepositoryMap) {
        this.diaryRepositoryMap = diaryRepositoryMap;
    }
    private DiaryRepository getDiaryRepository(MemoryType memoryType) {
    DiaryRepository repository = diaryRepositoryMap.get(memoryType);
        if (repository == null) {
            throw new IllegalArgumentException("해당 MemoryType에 맞는 Repository가 없습니다: " + memoryType);
        }
        return repository;
    }
}

public interface DiaryRepository {
    void save(Diary diary);
    void patch(long id, String body);
    void delete(long id);
    void restore(long id);
    List<Diary> findAll();
}

public class MemoryDiaryRepository implements DiaryRepository {}

public class FileDiaryRepository implements DiaryRepository {}
```

## 📍PR 링크

https://github.com/AND-SOPT-SERVER/jaeyun.park/pull/1

https://github.com/AND-SOPT-SERVER/jaeyun.park/pull/2

---

# 상아

### 💡일기 조회 기능

- DiaryRepository

```java
    List<Diary> findAll(){
        final List<Diary> diaryList = new ArrayList<>();

        for(long index = 1; index <= numbering.longValue() ; index++){
            final String body = storage.get(index);
            if (body != null){
                diaryList.add(new Diary(index, body));
            }
        }
        return diaryList;
    }
```

- DiaryService

```java
    List<Diary> getDiaryList() {
        return diaryRepository.findAll();
    }
```

- DiaryController

```java
    final List<Diary> getList() {
        return diaryService.getDiaryList();
    }
```

일기가 삭제될 경우, `body`가 `null`인 일기는 조회되지 않도록 if 구문을 추가해 두었습니다.

### 💡일기 작성 기능

- 글자 수 제한 30자 이내

```java
    final void post(final String body) {
            if(body.length() > 30){
                System.out.println("일기는 30자 이내로 작성해 주세요.");
                throw new IllegalArgumentException();
            }
        diaryService.writeDiary(body);
    }
```

호출자가 인수로 부적절한 값을 넘기므로 표준 예외인 `IllegalArgumentException()`를 추가했습니다.

### 💡일기 수정 기능

- DiaryRepository

```java
    void patch(final Long id,final String body){
        final List<Diary> diaryList = new ArrayList<>();
        storage.put(id, body);
    }
```

- DiaryService

```java
    void patchDiary(final Long id, final String body){
        diaryRepository.patch(id, body);
    }
```

- DiaryController

```java
    final void patch(final String id, final String body) {
        diaryService.patchDiary(Long.parseLong(id), body);
    }
```

`Long.parseLong`을 통해 `String`으로 들어오는 `id`값을 `Long` 타입으로 변환했습니다.

### 💡일기 제거 기능

- DiaryRepository

```java
    void delete(final Long id){
        final String body = storage.get(id);
        storage.remove(id);
    }
```

- DiaryService

```java
    void deleteDiary(final long id){
        diaryRepository.delete(id);
    }
```

- DiaryController

```java
    final void delete(final String id) {
        diaryService.deleteDiary(Long.parseLong(id));

    }
```

`Long.parseLong`을 통해 `String`으로 들어오는 `id`값을 `Long` 타입으로 변환했습니다.

### 💡삭제된 일기 복구

- DiaryRepository.java

```java
    private final Map<Long, String> deletedStorage = new ConcurrentHashMap<>();
    void delete(final Long id){
        final String body = storage.get(id);
        deletedStorage.put(id, body); // 삭제될 때 `deletedStorage`에 삭제된 내용  추가
        storage.remove(id);
    }

    void restore(final Long id){
        final String body = deletedStorage.get(id); // id 값으로 `deletedStorage`에서 삭제된 내용 불러옴
        storage.put(id, body); // storage에 삭제된 내용 추가
    }
```

### 💡 일기 수정 횟수 제한 (하루에 2번)

- DiaryRepository.java

```java
    private final AtomicLong patchCount = new AtomicLong();

  void patch(final Long id,final String body){
          if (patchCount.get() < 2){
              storage.put(id, body);
              patchCount.addAndGet(1);
              System.out.println("일일 일기 수정 잔여 횟수는 "+ (2-patchCount.get())+"회입니다!");
          } else{
              System.out.println("일기 수정은 하루에 2번까지 가능합니다");
          }
      }
```

`patchCount`를 추가하여 일기의 수정 횟수가 2회 이하일 때 `patchCount`가 1씩 증가하도록 구현했습니다.

```java
    private final LocalDate initialDate = LocalDate.now();
    private LocalDate firstPatchDate = initialDate;

  void patch(final Long id,final String body){
     final LocalDate currentPatchDate =  LocalDate.now();
      if (!firstPatchDate.isEqual(currentPatchDate)) {
          patchCount.set(0);
          firstPatchDate = currentPatchDate;
      }
      if (patchCount.get() < 2){
          if (patchCount.get() == 0){
              firstPatchDate=currentPatchDate;
          }
          storage.put(id, body);
          patchCount.addAndGet(1);
          System.out.println("일일 일기 수정 잔여 횟수는 "+ (2-patchCount.get())+"회입니다!");
      } else{
          System.out.println("일기 수정은 하루에 2번까지 가능합니다");
      }
    }
```

`patch` 시점의 날짜(`currentPatchDate`)를 받아와 처음 수정된 시점의 날짜(`firstPatchDate`)와 비교합니다.

만약 처음 수정된 날짜와 현재 날짜가 다를 경우, 하루가 지난 것으로 판단하여 `patchCount` 횟수를 0으로 초기화하고, `firstPatchDate`를 현재 날짜인 `currentPatchDate`로 업데이트합니다.

## 📍새로 알게 된 점

- `날짜`/`시간` 관련 클래스`LocalDate`: 서버가 위치한 local의 날짜 정보를 표현하는 클래스`LocalTime`: 서버가 위치한 local의 시간 정보를 표현하는 클래스`LocalDateTime`: 서버가 위치한 local의 날짜와 시간을 표현하는 클래스`Instant`: `time-zone`을 갖는 날짜와 시간을 표현하는 클래스

=> 정확한 시간 계산 혹은 절대적 시간이 필요할 경우 `Instant` 사용 권장

=> 서버가 위치한 지역 외 특정 지역에서의 시간, 날짜 정보가 필요할 경우 `Instant`에 time-zone 정보 사용 권장

=> 유효기간, 만료일 계산 등 시간대가 중요하지 않은 로직을 구현할 경우 `Local~~~` 사용

### 1) HashMap 사용 시의 고민..

• 일기 삭제될 경우 `body`가 `null`로 나타나 일기 조회 시 `body`가 `null`인 부분은 출력되지 않도록 했는데, 이 방법이 최선일까 고민이 되었던 것 같숨니다… 

### 2) mutable 객체의 올바른 사용...?!

```java
    private final AtomicLong numbering = new AtomicLong();
    private final AtomicLong patchCount = new AtomicLong();
    private final LocalDate initialDate = LocalDate.now();
    private LocalDate firstPatchDate = initialDate;
```

firstPatchDate는 날짜 변경에 따라 새로운 날짜로 업데이트가 되어야 하는 값인데, private final로 작성할 시 초기화가 되지 않아 별도의 `firstDate`를 추가해 두었습니다. 이때, `firstPatchDate`를 따로 정의하지 않고 LocaleDate를 업데이트 하는 방법이 있을지, 혹은`private LocalDate firstPatchDate = initialDate;` 만 정의해 두어도 괜찮을지 고민이 되었습니다.

→ 코드 토크를 통해 해결 완료! 

### 3) `LocalDate`의 문자열 비교

`firstPatchDate == currentPatchDate`로 문자열 비교가 되지 않더라고요... 일단

`isEqual`을 사용해 해결했는데, 비교 연산자 `==`가 왜 안 통했는지 잘 모르겠더라고요...

콘솔로 찍어봤을 때 `yyyy-mm-dd` 형태로 나왔고, `firstPatchDate.toString() == currentPatchDate.toString()` 으로 했을 때도 비교 연산자가 통하지 않아 요 부분이 궁금했습니다....

## 📍PR 링크

---

[[1차 세미나 과제] 필수 과제 구현 by Ivoryeee · Pull Request #3 · AND-SOPT-SERVER/sangah.park](https://github.com/AND-SOPT-SERVER/sangah.park/pull/3)

---

[[1차 세미나 과제] 선택 과제 구현 by Ivoryeee · Pull Request #4 · AND-SOPT-SERVER/sangah.park](https://github.com/AND-SOPT-SERVER/sangah.park/pull/4)

# 세희

## 📍구현 과정

- **POST - (필수과제 : 일기 글자수 제한)**
    - 글자 수를 30자로 제한하여, 30자를 넘기면 exception을 발생시키게 하였습니다.

- **DELETE - (필수과제 : 일기 삭제 기능 추가)**
    - 입력받은 `id`의 type이 `String`이기 때문에 `DiaryController.java`에서 `Long`으로 타입 변환하여 전달하였습니다.
    
- **Patch - (필수과제 : 일기 수정 기능 추가)**
    - DELETE에서 했던 것처럼 타입 변환하였습니다.
    
- **RESTORE - (선택과제 : 삭제된 일기 복구 기능 추가)**
    - 삭제된 일기와 관련한 `DeletedDiary` 클래스를 만들었습니다.
        - 일기의 `id`, `body`, 삭제 시간 `LocalDateTime`을 field로 가집니다.
    - 삭제된 일기를 저장하는 공간인 `delStorage`를 만들었습니다.
    - `DiaryRepository.java`에서 일기가 삭제될 때 삭제된 일기가 `delStorage`에 저장됩니다.
    - 삭제된지 이틀이 지난 일기 항목은 `delStorage`에서도 삭제됩니다.
    
    ```c
        //DiaryRepository.java
       
        
        //id를 입력받아서 해당 id의 삭제된 일기 복구
        void rest(Long id){
            DeletedDiary deletedDiary = delStorage.remove(id);
            storage.put(id, deletedDiary.getBody());
        }
    		
    		
    		//만료된 일기 삭제
        public void expire(){
            LocalDateTime now = LocalDateTime.now(); //현재 시간을 불러오기
            delStorage.entrySet().removeIf(entry -> {
                //entrySet : Map의 모든 항목 Set으로 반환.
                //removeIf : 조건 만족하는(return이 True인) 항목 삭제.
                //entry -> {...} : 람다 표현식.
                DeletedDiary deletedDiary = entry.getValue();
                return deletedDiary.getDelTime().plusDays(2).isBefore(now);
                //deletedDiary 객체의 deltime을 가져오고, 이틀을 더한 시간이 현재 시간보다 전이라면 => 삭제된지 이틀이 지났다면
            });
        }
    ```
    

## 📍고민 내용

- **미구현 과제 관련**
    - db에 migration하는 방식으로 일기를 저장할 수 있을 것 같다고 생각했습니다.
    - 날짜가 바뀔 때마다 일기 수정 횟수를 count하는 counter를 0으로 초기화하고, 수정 발생 시 카운터를 증가시키며 횟수를 제한할 수 있을 것 같습니다.
- **추가 관련**
    - restore 기능을 구현 할 때, Diary에 삭제 여부를 나타내는 boolean필드를 추가하는 방식으로 해도 괜찮을 것 같습니다.
    - 메서드 명의 경우 복구를 rest, 수정을 mod와 같이 약어로 쓰는 것 대신 restore, modify처럼 아예 늘여서 이해하기 쉽게 적는 게 좋을 것 같다는 피드백이 있었는데, 이 편이 더 좋을 것 같습니다!!
    - 예외처리를 조금 더 꼼꼼하게 해야될 것 같습니다.
    - public, private를 잘 구분지어 사용하는 방법을 공부하였습니다.

## 📍PR 링크

https://github.com/AND-SOPT-SERVER/seahee.baek/pull/2

https://github.com/AND-SOPT-SERVER/seahee.baek/pull/3

---

# 💡 재민

## 📍구현 내용

- **Post**
    - 글자수를 30자로 제한한 뒤, 30자가 넘어가면 Controller 단계에서 
    `InvalidInputException` 을 발생시켰습니다

- **Delete**
    - 사용자에게서 받은 값이 String 타입이지만 Repository에 저장되는 id타입은 Long 타입이므로 `parseLong()` 메소드를 사용하여 Long타입으로 바꿔줬습니다
    - 이후 Repository에서 삭제된 뒤 `numbering` 값을 줄여주어 `get`을 하였을 때 `null`값이 출력되지 않도록 하였습니다

- **Patch**
    - delete기능과 마찬가지로 `parseLong` 메소드를 활용하여 Long타입으로 형변환을 해주어 넘겨줬습니다
    - 하루에 2번만 수정가능하도록 `AtomicLong` 타입의 `DayNumbering` 객체를 생성해주어 한 번 수정하면 `DayNumbering`값이 1씩 증가되도록 하였습니다. 2번을 넘기면 수정하지 못 하도록 콘솔 창에 경고메세지를 출력하였습니다
    
    ```cpp
     void patch(final Long id, String body){
                    if(DayNumbering.intValue()> 1){
                                    System.out.println("하루에 2번만 수정가능합니다");
                            }
                    else{
                            DayNumbering.addAndGet(1); 
                            storage.replace(id, body);
                            }
    
                    }
    ```
    

## 📍고민 내용

- **미구현 과제** -삭제된 일기 복구 기능 추가
    - 삭제한 일기를 따로 보관해두는 클래스를 만들어 사용자가 복구를 원하면 그 클래스에서 다시 호출할 수 있도록 구현하려고 하였습니다. 하지만 그렇게 하면 ‘메모리를 많이 잡아먹지 않을까?’ 라는 생각이 들었고 어떻게 해야 효율적으로 구현할 수 있을지 찾아보던 중 `soft delete`와 `hard delete`에 대해 알게 되었습니다. 이 내용에 대해 공부하여 삭제된 일기 복구 기능을 구현해보고자 합니다.
- **삭제 후 NULL값 출력**
    - 일기를 삭제 후 get을 하였을 때 id와 body모두가 출력되지 않는 것을 기대하였지만 null값이 출력되었습니다. 이를 해결하기 위해 Repository에서 삭제 후 numbering값을 1씩 줄여주어 출력이 되지 않게끔 구현하였습니다. 이 방법말고도 더 좋은 방법이 어떤 것이 있을까 고민하였습니다.

## 📍PR 링크

---

[https://github.com/AND-SOPT-SERVER/jaemin.gwag/pull/2](https://github.com/AND-SOPT-SERVER/jaemin.gwag/pull/2)

# 챌린지 과제

---

### String에 대해 고민해보세요.

- 대문자와 소문자 구분은 중요한가요? 어떻게 생각하세요?
    - 키워드: `mysql collation`
    
- `UTF`가 뭐에요?
    
    **UTF(Unicode Transformation Format)**
    
    > ***유니코드***를 인코딩하는 방식 중 하나로, 각 문자를 바이트 단위로 변환.
    > 
    
    > UTF-8, UTF-16, UTF-18 등의 형식 존재
    > 
    
    **유니코드* : 전 세계의 모든 문자를 표현할 수 있도록 고안된 문자 집합. 
    
    |  | UTF-8 | UTF-16 | UTF-18 |
    | --- | --- | --- | --- |
    | 인코딩 길이 범위 | 1byte - 4byte | 2byte or 4byte | only 4byte |
    | 한글 바이트 크기 | 3byte | 2byte | 4byte |
    | 이모지 바이트 크기 | 4byte | most 4byte | 4byte |
- `StringBuilder`를 사용하면 어떤 이점이 있는 거죠?
    
    ## 📍String vs StringBuilder vs StringBuffer
    
    ### 💡 String
    
    > String은 불변 (immutable) 자료형이다!
    > 
    
    ### 불변성 (immutable)
    
    `String`은 변경 불가능한 문자열 객체를 생성하며, 한번 문자열이 생성된 이후 이가 할당된 공간은 절대 변하지 않는다!
    
    ![https://velog.velcdn.com/images/ivoryeee/post/e1342c48-05c9-47fa-acef-d70b60922bf4/image.png](https://velog.velcdn.com/images/ivoryeee/post/e1342c48-05c9-47fa-acef-d70b60922bf4/image.png)
    
    이를 보면 `String` 문자열이 `Value`라는 인스턴스 문자에 문자형 배열로 저장되어 있는 걸 볼 수 있는데 이는 상수형으로 저장돼 있어 값이 불변한 것이다.
    
    ```java
    String str = "AND SOPT";
    str = str + "Server";
    
    System.out.println(str); // AND SOPT Server
    
    ```
    
    이와 같이 문자열이 업데이트 되는 상황은 뭔데?! 싶을 수 있을 것 같다.
    
    앞선 코드에서는 `AND SOPT`라는 문자열과 `AND SOPT Server` 의 메모리가 할당된 영역이 다르다.
    즉, `AND SOPT Server`이라는 저장 영역을 새로 생성하고, 기존 `AND SOPT`의 참조 영역을 그대로 참조하는 것!
    
    ### 💡String이 가지는 한계
    
    그러나 ...
    
    문자열이 업데이트 될 때마다 새로운 객체를 생성하는 작업은 다른 작업에 비해 많은 시간이 소요된다. 또한, 여러 문자열을 연결해 많은 업데이트가 이루어진다면 중간 문자열 객체가 너무 많이 생성돼 `코드의 비효율성`이 높아진다.
    
    이러한 한계점을 극복하기 위해 나타난 것이
    `StringBuilder`과 `StringBuffer`이다!
    
    ### 💡 StringBuilder / StringBuffer
    
    `StringBuilder`과 `StringBuffer`은 변경 가능한 문자열 객체 생성하며, 버퍼 크기의 확장에 유연하게 대응한다.
    
    기존 문자열의 삭제, 추가 등 변경에 메모리를 유연하게 할당하므로 `String` 에서의 반복적인 객체 생성으로 인한 비효율을 줄일 수 있다.
    
    StringBuilder과 StringBuffer은 상수(final) 키워드가 존재하지 않는다.
    
    ![https://velog.velcdn.com/images/ivoryeee/post/843ef159-230d-4613-ac22-3aa89757e059/image.png](https://velog.velcdn.com/images/ivoryeee/post/843ef159-230d-4613-ac22-3aa89757e059/image.png)
    
    - `StringBuilder`의 사용 예시
    
    ```java
    public class Main {
    	public static void main(String[] args){
        	StringBuilder strBuilder = new StringBuilder;
            strBuilder.append("SOPT");
            strBuilder.append("Server");
    
            String sql = strBuilder.toString();
        }
    }
    
    ```
    
    `append` 메서드를 사용해 문자열을 연결해 주며 SQL문이나 HTML 코드를 생성하는 등의 작업에서 성능을 크게 높일 수 있다.
    
    - `StringBuffer`의 사용 예시
    
    ```java
    public class Main {
    	public static void main(String[] args){
        	StringBuffer strBuffer = new StringBuffer;
            StringBuffer.append("SOPT");
            StringBuffer.append("Server");
    
            String sql = strBuffer.toString();
        }
    }
    
    ```
    
    `append` 메서드를 사용해 문자열을 연결해 주며 SQL문이나 HTML 코드를 생성하는 등의 작업에서 성능을 크게 높일 수 있다.
    
    ### 💡 StringBuilder과 StringBuffer의 차이점은...
    
    앞선 설명과 같이 문자열 연산으로 인해 기존 객체의 공간이 부족하게 될 경우 두 클래스는 버퍼 크기를 확장하며 유연하게 동작하는데, `동기화 여부`에서 각 클래스는 차이점을 지닌다.
    
    `StringBuffer`은 각 메서드 별로 `Synchronized Keyword`가 존재해 멀티스레드 환경에서도 동기화를 지원하는 반면에 `StringBuilder`은 동기화를 보장하지 않는다.
    
    따라서, `멀티 스레드 환경`에서는 값 동기화 보장을 위해 `StringBuffer`을 사용하는 게 유리하고, `단일 스레드 환경`에서는 `StringBuilder`을 사용하는 게 성능상 유리하다.
    
    ### 💡정리해 보면
    
    - `String`은 짧고 간단한 문자열 연산에서 사용할 수 있다
    - `StringBuilder` 과 `StringBuffer`은 값 변경 시 새로운 객체를 만드는 `String` 보다 훨씬 빠르기 때문에 문자열 연산이 빈번할 때 사용하기에 유리하다.
    `StringBuilder`은 `단일 스레드 환경`에서 문자열 연산을 수행할 때 유리하다.
    `StringBuffer`은 `멀티 스레드 환경`에서 문자열 연산을 수행할 때 유리하다.
    
    상황에 따라 알맞은 클래스를 사용해 봅시다아

**Comment by daehwan2da** [comment]
고생하셨습니다~ 정리 잘해서 자기꺼로 만드시길바랄게요.

> 날짜/시간 관련 클래스LocalDate: 서버가 위치한 local의 날짜 정보를 표현하는 클래스LocalTime: 서버가 위치한 local의 시간 정보를 표현하는 클래스LocalDateTime: 서버가 위치한 local의 날짜와 시간을 표현하는 클래스Instant: time-zone을 갖는 날짜와 시간을 표현하는 클래스
=> 정확한 시간 계산 혹은 절대적 시간이 필요할 경우 Instant 사용 권장
> 
> => 서버가 위치한 지역 외 특정 지역에서의 시간, 날짜 정보가 필요할 경우 Instant에 time-zone 정보 사용 권장
> 
> => 유효기간, 만료일 계산 등 시간대가 중요하지 않은 로직을 구현할 경우 Local~~~ 사용

시간은 클라이언트와 서버간의 소통에 있어도 중요한 인터페이스요소인데요. 이 부분은 CS 스터디에서 따로 다루도록할게요~
